#spring.application.name=ai-stream-chat

spring:
  application:
    name: ai-stream-chat

server:
  port: 8080

anthropic:
  api-key: ${ANTHROPIC_API_KEY:mock}   # ???? ??? mock ??
  base-url: https://api.anthropic.com
  model: claude-sonnet-4-20250514
  max-tokens: 1024

logging:
  level:
    com.streamchat: DEBUG
    reactor.netty.http.client: INFO